# -*- coding: utf-8 -*-
"""
tasks/help_data.py — Strukturierte Hilfetexte pro Task.

Wird vom Hilfe-Fenster der GUI gelesen (main.py → _open_help).
Schema pro Eintrag:
    {
        "title":   Titel,
        "group":   Vorbereitung | Analysen | Extras | Export,
        "purpose": Zweck in 1-2 Sätzen,
        "input":   Welche GEDCOM-Felder/Vorgänger-Tasks gebraucht werden,
        "output":  Welche Excel-Sheets / Dateien erzeugt werden,
        "details": Ausführliche Beschreibung,
        "tips":    Optional: Tipps zur Nutzung,
    }
"""

HELP_ENTRIES: dict = {
    # ── Vorbereitung ───────────────────────────────────────────────────────────
    "load_gedcom": {
        "title":   "GEDCOM laden",
        "group":   "Vorbereitung",
        "purpose": "Liest die Stammbaumdatei (.ged oder .ftm) und bereitet alle Daten für die Analysen vor.",
        "input":   "Stammbaumdatei (GEDCOM 5.5 oder Family Tree Maker .ftm). Auto-Erkennung des Formats anhand SQLite-Header bei .ftm.",
        "output":  "Befüllt den State mit individuals + families. Erkennt Militär-Symbole ✠ ★ ⚔ ‡ und mig.-Marker im Namen. Liest EMIG/IMMI-Events.",
        "details": "Pflicht-Task. Ohne ihn können keine anderen Analysen laufen. Lädt auch die location_data.json für die Orts-Hierarchie-Parsung. Bei Familienarchiven > 100k Personen dauert das Einlesen 5–15 Sekunden.",
        "tips":    "Wird der Pfad in der UI geändert, wird er nach Klick auf 'Starten' persistiert (config_user.json). Beim nächsten Start ist er vorausgewählt.",
    },
    "load_cache": {
        "title":   "State-Cache laden (inkrementell)",
        "group":   "Vorbereitung",
        "purpose": "Lädt einen zuvor gespeicherten Analyse-State und überspringt alle Vor-Berechnungen, wenn die GEDCOM unverändert ist.",
        "input":   "~/.ahnen-cache.pkl (von 'State-Cache speichern' erzeugt). Vergleicht SHA-256 der aktuellen GEDCOM mit dem im Cache.",
        "output":  "Ersetzt den kompletten _state mit dem zwischengespeicherten Stand.",
        "details": "Workflow für Wiederholungs-Läufe: einmal komplett rechnen → 'State-Cache speichern' aktivieren → beim nächsten Run nur 'State-Cache laden' + gewünschte Export-Tasks aktivieren. Spart bei 130k Personen ~90 Sekunden.",
        "tips":    "Bei GEDCOM-Änderung wird der Cache automatisch verworfen und ein komplettes Re-Rechnen erforderlich.",
    },

    # ── Analysen ──────────────────────────────────────────────────────────────
    "cousins": {
        "title":   "Verwandtschafts-/Cousin-Analyse",
        "group":   "Analysen",
        "purpose": "Berechnet für jede mit der Root-Person verwandte Person die exakte Verwandtschaftsbezeichnung.",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "Sheet 'Cousin Beziehungen' — ein Eintrag pro Verwandtem. Bei 130k-Tree typisch 60–70k Einträge.",
        "details": "Nutzt BFS-Algorithmus, ermittelt für jeden Verwandten die Tiefe zum jüngsten gemeinsamen Ahnen mit Root und übersetzt das in deutsche Labels: Elternteil, Großelternteil, Cousin 1.–N. Grades, Urgroßonkel, etc.",
        "tips":    "Wichtige Grundlage für DNA-cM-Schätzung und MRCA-Finder — diese Tasks bauen auf den Cousin-Ergebnissen auf.",
    },
    "endogamy": {
        "title":   "Endogamie & Top-Ahnen",
        "group":   "Analysen",
        "purpose": "Identifiziert Orte mit hoher Endogamie und die wichtigsten Stamm-Ahnen.",
        "input":   "individuals + families + ROOT_ID + Ortsdaten.",
        "output":  "Sheets 'Endogamie Scores' (pro Ort), 'Top Ahnen' (wichtigste Stamm-Ahnen ohne weitere Vorfahren).",
        "details": "Endogamie-Score pro Ort = 1 - (distinkte Nachnamen / Personen). Top-Ahnen sind Vorfahren, deren eigene Eltern unbekannt sind — typische Startpunkte für Recherche.",
    },
    "migration": {
        "title":   "Migrationsrouten + Wellen + Korrelation",
        "group":   "Analysen",
        "purpose": "Vollständige Migrationsanalyse: einzelne Routen, komprimierte Familien-Routen, Wellen über Zeit, demografische Korrelationen.",
        "input":   "individuals (BIRT.PLAC, EMIG, IMMI, mig.-Marker) + families + Ortsdaten.",
        "output":  "Vier Sheets: 'Migrationsrouten Detail', 'Migrationsrouten Compressed' (Familien-Aggregate), 'Migrationswellen', 'Korrelation Migration-Demografie'.",
        "details": "Erkennt Migrationen über: (1) EMIG/IMMI-Events, (2) mig.-Marker im Namen, (3) Geburts- vs. Sterbeort in verschiedenen Ländern. Wellen werden über DBSCAN-ähnliches Zeit-Clustering identifiziert.",
    },
    "military": {
        "title":   "Militäranalyse",
        "group":   "Analysen",
        "purpose": "Detailanalyse aller militärischen Einträge: Streitkraft, Kriegszuordnung, Sterbealter-Klassen.",
        "input":   "individuals mit Militär-Symbolen ✠ (Deutsche), ★ (Andere), ⚔ (Gefallene).",
        "output":  "Sheet 'Militärdienst Details' und 'Symbol-Statistik' (Gesamt-Counts pro Symbol).",
        "details": "Klassifiziert Sterbealter (kurz ≤25 J. / mittel 26–35 / lang >35), ordnet Sterbedaten möglichen Kriegen zu (Dreißigjähriger Krieg, Napoleonische Kriege, Deutsch-Französisch, WWI, WWII).",
    },
    "demographics": {
        "title":   "Demografische Statistiken",
        "group":   "Analysen",
        "purpose": "Lebenserwartung, Heiratsalter, Kinderzahl, Kindersterblichkeit pro Epoche & Geschlecht.",
        "input":   "individuals mit Geburts-/Sterbedaten + families.",
        "output":  "Sheet 'Demografische Statistik' (Epoche × Geschlecht) und 'Umfassende Statistiken' (Gesamtkennzahlen).",
        "details": "Epochen: vor 1800, 1800–1850, 1850–1900, 1900–1950, nach 1950. Berechnet Median, Min, Max für Lebensspannen.",
    },
    "surnames": {
        "title":   "Familiennamen & Geburtsländer",
        "group":   "Analysen",
        "purpose": "Top-100 Familiennamen und Top-Geburtsländer mit Zeitspannen.",
        "input":   "individuals.",
        "output":  "Sheets 'Familiennamen Häufigkeit', 'Geburtsland Verteilung'.",
        "details": "Spaltet auch nach Geschlecht und gibt Geschlechterverteilung pro Nachname/Land aus.",
    },
    "genetics": {
        "title":   "Genetik (Inzucht + Pedigree Collapse)",
        "group":   "Analysen",
        "purpose": "Wright's F-Koeffizient pro Person, Pedigree-Collapse pro Generation, DNA-cM-Schätzung pro Verwandtem.",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "Sheets 'Inzuchtkoeffizient', 'Pedigree Collapse Generationen', 'Pedigree Collapse Mehrfach'.",
        "details": "F=0 bei nicht-konsanguinen Verbindungen, F=1/16 bei Cousin-Ehe, F=1/4 bei Geschwister-Ehe. Pedigree Collapse zeigt pro Generation: theoretische Slots (2^n) vs. tatsächliche eindeutige Vorfahren.",
        "tips":    "Die Kinship-Berechnung nutzt Henderson Tabular Method (rekursiv + memoisiert) — mathematisch korrekt auch bei tiefem Implex.",
    },
    "history": {
        "title":   "Historischer Kontext & Überlebenszeitanalyse",
        "group":   "Analysen",
        "purpose": "Ordnet Personen 19 historischen Ereignissen zu (1618–1973) und berechnet Survival-Kurven pro Geburts-Kohorte.",
        "input":   "individuals + families + Ortsdaten + ROOT_ID.",
        "output":  "Sheets 'Hist. Kontext Ereignisse', 'Hist. Kontext Personen', 'Überleben Kohorten', 'Überlebenskurven', 'Historische Trends'.",
        "details": "Kaplan-Meier-Kurven pro Jahrhundert-Kohorte. Generationenlängen werden bidirektional (Ahnen UND Nachfahren) berechnet.",
    },
    "names": {
        "title":   "Namensmorphologie (Kölner Phonetik)",
        "group":   "Analysen",
        "purpose": "Gruppiert Schreibvarianten desselben Namens automatisch via Kölner Phonetik + Levenshtein.",
        "input":   "individuals.",
        "output":  "Sheets 'Namensvarianten (Kölner Phonetik)', 'Namensvarianten Personen'.",
        "details": "Findet z.B. Müller/Mueller/Möller in einer Gruppe. Hilft bei der Erkennung von Schreibfehler-bedingten Doppeleinträgen.",
    },
    "data_quality": {
        "title":   "Datenvollständigkeits-Score",
        "group":   "Analysen",
        "purpose": "Bewertet pro Person die Datenqualität auf einer 0–100-Skala.",
        "input":   "individuals + families.",
        "output":  "Sheets 'Datenvollständigkeit Personen', '… Nachnamen', '… Epochen'.",
        "details": "Score pro Person basiert auf vorhandenen Feldern: Name (mit/ohne Surname), Geburtsjahr, Geburtsort, Sterbejahr, Sterbeort, Ehepartner, Eltern, Kinder. Aggregation auf Nachname- und Epoche-Ebene.",
    },
    "anomalies": {
        "title":   "Anomalien & Doubletten & Inseln",
        "group":   "Analysen",
        "purpose": "Findet implausible Datenkombinationen (Geburt nach Tod, zu junge Eltern, Zukunfts-Daten), potenzielle Duplikate und unverbundene Personen.",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "Drei Sheets: 'Daten-Anomalien' (KRITISCH/WARNUNG/HINWEIS), 'Potenzielle Doubletten' (mit Konfidenz-Score), 'Unerreichbare Personen'.",
        "details": "Anomalie-Schwellen: Mutter <12 J. oder >55 J., Vater <12 J. oder >80 J., Geschwisterabstand >25 J., Lebensalter >110, Heirat <14 oder >90 J. Doubletten-Detektor nutzt Levenshtein + 60-Einträge-Vornamen-Synonymtabelle (Hans↔Johannes, Fritz↔Friedrich, …).",
    },
    "dna_overview": {
        "title":   "DNA-Überblick (Ancestry-Datenbank)",
        "group":   "Analysen",
        "purpose": "Liest die Ancestry-DNA-SQLite-Datenbank und erstellt eine Übersicht über geladene Kits, Match-Zahlen, Top-Matches und Cluster.",
        "input":   "ancestry/ancestry_dna.db (wird vom Ancestry-DNA-Tool befüllt).",
        "output":  "Sheet 'DNA-Überblick (Ancestry)' mit Kit-Name, Match-Anzahl, Top-5, Leeds-Cluster, Endogamie-Markierungen.",
        "tips":    "Nur sinnvoll wenn das Ancestry-DNA-Tool bereits Matches heruntergeladen hat. Datenbankpfad: ancestry/ancestry_dna.db.",
    },
    "dna_cm": {
        "title":   "DNA-cM-Schätzung",
        "group":   "Analysen",
        "purpose": "Schätzt für jeden Verwandten die zu erwartenden gemeinsamen DNA-cM-Werte aus dem Stammbaum.",
        "input":   "individuals + families + ROOT_ID + Cousin-Ergebnisse.",
        "output":  "Sheet 'DNA-cM-Schätzung' (Kinship Φ, erwartete cM, DNA-Klasse).",
        "details": "Formel: erwartete cM ≈ Φ × 2 × 7000. Klassen orientiert an Ancestry/MyHeritage-Skala: Elternteil/Kind ~3500 cM, Vollgeschwister ~2600, Cousins 1°/2°/3° ~875/220/75.",
        "tips":    "Bei eigenem DNA-Test: Werte aus Ancestry hier abgleichen → wer in deinem Baum passt zu einem gemessenen Match-Wert?",
    },
    "sibling_namedrift": {
        "title":   "Geschwister-Statistiken & Namensdrift",
        "group":   "Analysen",
        "purpose": "Geburtsabstände in Familien + temporale Verbreitung jedes Vornamens.",
        "input":   "individuals + families.",
        "output":  "Sheets 'Geschwister-Statistiken' (pro Familie: Spanne, Min/Max-Abstand, Zwillinge), 'Namensdrift (Vornamen)' (pro Name: Peak-Dekade, Spanne).",
        "details": "Findet 'Zwillingsverdacht' bei Geschwistern mit gleichem Geburtsjahr und zeigt die zeitliche Drift von Vornamenstrends.",
    },
    "seasonality": {
        "title":   "Saisonalität (Monatsverteilung)",
        "group":   "Analysen",
        "purpose": "Verteilung von Geburten, Heiraten, Sterbefällen und geschätzten Empfängnissen über die 12 Monate pro Epoche.",
        "input":   "individuals + families (mit Monats-Information im DATE-String).",
        "output":  "Vier Sheets: 'Geburts-Monate', 'Heirats-Monate', 'Sterbe-Monate' (nach Altersklasse), 'Empfängnis-Monate' (Geburt − 9 Monate).",
        "details": "Zeigt traditionelle Heirats-Peaks (November/Mai bei Bauern), Säuglings-Sterbe-Sommerpeaks, Greisensterben im Winter.",
    },
    "snapshot": {
        "title":   "Stichjahr-Snapshot + Generationen-Overlap",
        "group":   "Analysen",
        "purpose": "Wer lebte zu bestimmten Stichjahren (1600, 1700, …, 2000)? Wie viele Generationen waren pro Jahrzehnt parallel am Leben?",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "Sheets 'Stichjahr-Snapshot' (Personen pro Stichjahr nach Geschlecht/Alter), 'Lebende Generationen' (pro Jahrzehnt).",
        "details": "Bei unbekanntem Sterbedatum wird die Person als lebend angenommen, wenn Geburtsjahr ≤ Stichjahr ≤ Geburtsjahr + 100.",
    },
    "spatial": {
        "title":   "Räumliche Lebensgeschichte",
        "group":   "Analysen",
        "purpose": "Heirats-Migration der Frauen, Lebens-Triangulation (Geburt→Heirat→Tod), Sesshaftigkeit pro Familie, Nachname×Region-Matrix.",
        "input":   "individuals + families + Ortsdaten + ROOT_ID.",
        "output":  "Vier Sheets: 'Heirats-Migration', 'Lebens-Triangulation', 'Sesshaftigkeit pro Familie', 'Nachname × Region'.",
        "details": "Klassifiziert Bewegungen als Lokal/Region/Land. Sesshaftigkeits-Score pro Familie = 1 / (distinkte Orte + 1).",
    },
    "family_structure": {
        "title":   "Erweiterte Familienstruktur",
        "group":   "Analysen",
        "purpose": "Mehrfachehen, Altersdifferenz Ehepaare, Reproduktive Spanne der Mütter, Kinderlosigkeit, Zwillinge.",
        "input":   "individuals + families.",
        "output":  "Fünf Sheets: 'Mehrfach-Ehen', 'Alters-Differenz Ehepaare', 'Reproduktive Spanne (Mütter)', 'Kinderlosigkeits-Rate', 'Zwillinge / Mehrfachgeburten'.",
        "details": "Mehrfachehen markiert Witwer/Witwen (Vor-Ehepartner gestorben). Altersdifferenz aggregiert pro Epoche mit Median/Min/Max.",
    },
    "lineage": {
        "title":   "Linien-Analysen (Y, Mt, Quartile, Aussterben)",
        "group":   "Analysen",
        "purpose": "Reine paternale Y-Linie, reine maternale Mt-Linie, 4-Quartile-Großeltern-Vergleich, Linien-Aussterben pro Nachname, Verzweigungs-Faktor.",
        "input":   "individuals + families + Ortsdaten + ROOT_ID.",
        "output":  "Fünf Sheets: 'Y-Linie (paternal)', 'Mt-Linie (maternal)', 'Großeltern-Quartile', 'Linien-Aussterben', 'Verzweigungs-Faktor'.",
        "details": "Y-Linie folgt nur Vater→Vater→… (DNA-Y-Vergleich). Mt-Linie folgt nur Mutter→Mutter→… (Mitochondrium-Vergleich). Quartile (PP/PM/MP/MM) zeigen Asymmetrien zwischen den 4 Großeltern-Linien.",
    },
    "naming_sociology": {
        "title":   "Namens-Soziologie (Patronyme, Junioren)",
        "group":   "Analysen",
        "purpose": "Patronyme (Mittlerer Vorname = Rufname des Vaters), Junioren (Erster Vorname = Vater-Vorname), Vornamen-Pool pro Familie.",
        "input":   "individuals + families.",
        "output":  "Drei Sheets: 'Patronyme', 'Junior-Detektor', 'Familien-Vornamen-Pool'.",
        "details": "Patronym-Tradition war im 17.–19. Jhd. weit verbreitet. Wiederverwendungs-Quote im Familien-Vornamen-Pool zeigt traditionsbewusste Familien.",
    },
    "imputation": {
        "title":   "Daten-Imputation (fehlende Daten)",
        "group":   "Analysen",
        "purpose": "Schätzt fehlende Geburtsjahre aus Familienkontext (Eltern, Kinder, Ehepartner, Geschwister).",
        "input":   "individuals + families.",
        "output":  "Sheet 'Geschätzte fehlende Daten' (mit Konfidenz-Klasse HOCH/MITTEL/NIEDRIG).",
        "details": "Kombiniert 4 Quellen: Eltern (+27), Kinder (Median − 27), Ehepartner (±3), Geschwister (±5). Konfidenz = HOCH wenn ≥2 Quellen mit Streuung ≤5 J.",
        "tips":    "Standardmäßig deaktiviert — wird nur bei explizitem Bedarf eingeschaltet.",
    },
    "cohort_extensions": {
        "title":   "Krisen-Kohorten & Eltern-Verlust",
        "group":   "Analysen",
        "purpose": "Vergleicht Lebensverläufe von Personen, die während historischer Krisen geboren wurden, mit Kontroll-Kohorten. Berechnet Alter beim Tod der Eltern pro Epoche.",
        "input":   "individuals + families.",
        "output":  "Sheets 'Krisen-Kohorten Folge', 'Eltern-Verlust-Alter'.",
        "details": "Pro historisches Ereignis: Kohorte = Geborene während des Ereignisses vs. Baseline = die 20 Jahre davor. Vergleicht Lebenserwartung, Heiratsalter, Kinderzahl.",
    },
    "research_helpers": {
        "title":   "Forschungs-Helfer (Brickwalls, Vorschläge, Quellen)",
        "group":   "Analysen",
        "purpose": "Brick-Wall-Detektor (gut belegte Personen ohne Eltern), Forschungs-Vorschläge nach Priorität, SOUR/OBJE-Inventar.",
        "input":   "individuals + families + GEDCOM-Datei (für SOUR-Parsing).",
        "output":  "Vier Sheets: 'Brick-Wall-Detektor' (Score ≥50), 'Forschungs-Vorschläge' (HOCH/MITTEL/NIEDRIG), 'Quellen-Inventar', 'Quellen-Qualität pro Person'.",
        "details": "Brick-Walls = die wichtigsten nächsten Recherche-Ziele. Forschungs-Vorschläge sind automatisch generierte Hinweise ('Suche Geburtseintrag in X um Jahr Y').",
        "tips":    "Die Brick-Wall-Liste ist die effizienteste 'next steps'-Liste für genealogische Recherche.",
    },
    "onomastics_endogamy": {
        "title":   "Onomastik & Endogamie-Bigraph",
        "group":   "Analysen",
        "purpose": "Religiöse/regionale Namensmuster (katholisch/protestantisch/germanisch) + Nachname × Nachname Heirats-Netz.",
        "input":   "individuals + families + Ortsdaten.",
        "output":  "Sheets 'Onomastik (Namensmuster)' und 'Endogamie-Netzwerk (Nachname×Nachname)'. Zusätzlich GraphML-Datei endogamy_network.graphml.",
        "details": "Onomastik klassifiziert Vornamen anhand 60+ Listen. Endogamie-Bigraph zeigt, welche Nachnamen-Paare am häufigsten miteinander heirateten.",
    },
    "sosa": {
        "title":   "Sosa-Stradonitz-Ahnentafel",
        "group":   "Analysen",
        "purpose": "Klassische internationale Ahnen-Nummerierung (Root=1, Vater=2, Mutter=3, …) inkl. Implex-Erkennung.",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "Sheet 'Sosa-Stradonitz-Ahnentafel' — eine Zeile pro Sosa-Nummer, sortiert.",
        "details": "Bei Pedigree-Collapse hat eine Person mehrere Sosa-Nummern (separate Spalte 'Implex'). Formel: Vater von N = 2N, Mutter von N = 2N+1.",
        "tips":    "Das ist der genealogische Welt-Standard. Jede Druck-Ahnentafel nutzt diese Nummerierung.",
    },
    "familysearch": {
        "title":   "FamilySearch-Vergleich (Suchlinks)",
        "group":   "Analysen",
        "purpose": "Generiert pro Ahn vorbereitete FamilySearch-Such-URLs (Quellen-Datenbank + Family Tree).",
        "input":   "individuals (vorzugsweise root_related_ids).",
        "output":  "Sheet 'FamilySearch-Vergleich' — zwei klickbare URLs pro Person, sortiert nach Such-Qualität.",
        "details": "Kein API-Key/OAuth nötig — der Browser handlet Auth. Such-Qualität (0–100) basiert auf vorhandenen Feldern: Name+Surname, Geburtsjahr, Geburtsort, Sterbedaten.",
        "tips":    "Klicke eine URL → siehst sofort, ob die Person in FamilySearch existiert.",
    },

    # ── Extras ────────────────────────────────────────────────────────────────
    "network": {
        "title":   "Familiennetzwerkanalyse",
        "group":   "Extras",
        "purpose": "Degree-Centrality, Betweenness, Brückenpersonen im Familien-Graph.",
        "input":   "individuals + families.",
        "output":  "Sheet 'Familiennetzwerk' (per Person mit Centrality-Werten).",
        "details": "Standardmäßig deaktiviert — rechenintensiv. Wählt automatisch zwischen Fast (≤5k Personen), Optimized (≤50k), Detailed (>50k).",
    },
    "osnabrueck": {
        "title":   "Osnabrück-Region Spezialanalyse",
        "group":   "Extras",
        "purpose": "Region-spezifische Analyse für Wallenhorst, GMH, Hagen a.T.W., Osnabrück, Bohmte.",
        "input":   "individuals mit Ortsdaten in der Osnabrück-Region.",
        "output":  "Sheet 'Osnabrück Übersicht' + ein Sheet pro Gemeinde.",
        "details": "Strikte Hierarchie-Prüfung: Personen werden nur zugeordnet, wenn Land + Kreis stimmen.",
    },

    # ── Export ────────────────────────────────────────────────────────────────
    "export_excel": {
        "title":   "Excel-Export",
        "group":   "Export",
        "purpose": "Schreibt alle aktiven Analyse-Sheets in eine Excel-Mappe.",
        "input":   "Alle Analyse-Ergebnisse im State.",
        "output":  "genealogy_analysis_complete.xlsx (typisch 15–25 MB bei 130k-Tree).",
        "details": "Nutzt openpyxl im write-only-Modus → streaming, RAM-flach, atomar geschrieben (.tmp → rename).",
    },
    "export_json": {
        "title":   "JSON-Export",
        "group":   "Export",
        "purpose": "Metadaten-Zusammenfassung als JSON.",
        "input":   "State (Statistiken, Top-Listen).",
        "output":  "genealogy_results.json.",
        "details": "Klein (<1 MB). Enthält Versionsinfo, Statistiken, Top-20-Nachnamen, Top-10-Länder.",
    },
    "export_html": {
        "title":   "HTML-Übersicht",
        "group":   "Export",
        "purpose": "Selbsterklärende HTML-Datei mit Kernkennzahlen.",
        "input":   "State.",
        "output":  "family_tree.html (Dark Theme, keine externen Dependencies).",
        "details": "Tabellen für Gesamtstatistik, Top-20-Nachnamen, Top-10-Länder, Demografie pro Epoche, Migrationswellen.",
    },
    "export_timeline": {
        "title":   "HTML-Timeline",
        "group":   "Export",
        "purpose": "Chronologische Ereignis-Zeitlinie mit Live-Filter im Browser.",
        "input":   "individuals + families + root_related_ids.",
        "output":  "timeline.html mit JavaScript-Such-Filter.",
        "details": "Alle Geburten, Tode, Auswanderungen, Einwanderungen sortiert nach Jahr. Filter im Eingabefeld nach Person oder Ort.",
    },
    "export_graphml": {
        "title":   "GraphML-Export",
        "group":   "Export",
        "purpose": "Familiennetzwerk als GraphML-Datei für Gephi/yEd.",
        "input":   "individuals + families + (optional) root_related_ids.",
        "output":  "family_network.graphml.",
        "details": "Knoten = Personen, Kanten = Eltern→Kind + Ehepartner.",
    },
    "export_fanchart": {
        "title":   "Fan-Chart SVG",
        "group":   "Export",
        "purpose": "Klassischer radialer Ahnenfächer (5-Generationen-Tafel) als SVG.",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "fan_chart.svg — direkt im Browser/Inkscape öffenbar.",
        "details": "Paternale Linie in Blau, maternale in Pink, unbekannte Ahnen in Grau. Druckfertig.",
    },
    "export_dashboard": {
        "title":   "HTML-Dashboard mit Charts",
        "group":   "Export",
        "purpose": "Interaktives Single-File-Dashboard mit Chart.js und Tab-Navigation.",
        "input":   "State.",
        "output":  "dashboard.html (Single-File, eine CDN-Referenz zu Chart.js).",
        "details": "6 Tabs: Übersicht, Demografie, Migration, Namen, Geografie, Genetik. Dark Theme.",
    },
    "export_heatmap": {
        "title":   "Geburts-Heatmap (Leaflet)",
        "group":   "Export",
        "purpose": "Welt-Karte der Geburtsorte nach Land + Jahrhundert.",
        "input":   "individuals + Ortsdaten.",
        "output":  "birth_heatmap.html (Leaflet, CARTO-Dark-Tiles).",
        "details": "Circle-Marker mit Radius proportional zu log(Anzahl), Farbe nach dominantem Jahrhundert.",
    },
    "export_descendants": {
        "title":   "Subtree: Nachfahren der Root als GEDCOM",
        "group":   "Export",
        "purpose": "Schreibt nur den Nachfahren-Teilbaum der Root als eigene .ged-Datei.",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "descendants.ged (GEDCOM 5.5).",
        "details": "Enthält Nachfahren bis max 10 Generationen + deren Ehepartner.",
    },
    "export_ancestors": {
        "title":   "Subtree: Vorfahren der Root als GEDCOM",
        "group":   "Export",
        "purpose": "Schreibt nur den Vorfahren-Teilbaum der Root als eigene .ged-Datei.",
        "input":   "individuals + families + ROOT_ID.",
        "output":  "ancestors.ged.",
        "details": "Enthält Vorfahren bis max 12 Generationen.",
    },
    "export_sankey": {
        "title":   "Migrations-Sankey (HTML)",
        "group":   "Export",
        "purpose": "Migrationsflüsse als interaktives SVG-Sankey-Diagramm.",
        "input":   "Migration-Ergebnisse.",
        "output":  "migration_sankey.html (Pure-SVG, keine externen Libs).",
        "details": "Linke Spalte = Geburtsländer, rechte = Sterbeländer. Bandbreite proportional zur Anzahl.",
    },
    "save_cache": {
        "title":   "State-Cache speichern",
        "group":   "Export",
        "purpose": "Persistiert den kompletten _state nach ~/.ahnen-cache.pkl für inkrementelle Folge-Läufe.",
        "input":   "Alle bisher berechneten Analyse-Ergebnisse.",
        "output":  "~/.ahnen-cache.pkl (typisch 50–200 MB) + SHA-256 der GEDCOM.",
        "details": "Beim nächsten Lauf: 'State-Cache laden' + nur Export-Tasks aktivieren → übergeht alle Re-Berechnungen.",
    },
    "online_research": {
        "title":   "Online-Sterbedaten (Wikidata + GND)",
        "group":   "Analysen",
        "purpose": "Ergänzt fehlende Sterbejahre aus Wikidata und der Deutschen Nationalbibliothek (GND) — rein lesend, kein GEDCOM-Schreiben.",
        "input":   "Personen im GEDCOM ohne Sterbejahr.",
        "output":  "Vorschlags-Liste mit Quellen-URL und Konfidenz; kein automatisches Einpflegen.",
        "details": "Benötigt aktive Internetverbindung. Bei großen Bäumen (>5 000 Personen) kann der Lauf mehrere Minuten dauern.",
    },
    "book_statistics": {
        "title":   "Buch-Statistiken (21 Analysen)",
        "group":   "Analysen",
        "purpose": "Implementiert alle 21 demografischen Analysen aus 'The Village in the Field': Sterbespitzen, Heiratsdistanz, Auswanderer vs. Stayer, Hofnamen, Berufsstand u.v.m.",
        "input":   "Vollständig geladenes GEDCOM.",
        "output":  "Ergebnis-Dicts im _state; werden von Excel-, HTML- und Dashboard-Export genutzt.",
        "details": "Aktivieren, bevor Export-Tasks gestartet werden — export_gravity_map und export_cousins_map benötigen diese Analyse.",
    },
    "export_gravity_map": {
        "title":   "Karte: Demografischer Schwerpunkt (Zeitraffer)",
        "group":   "Export",
        "purpose": "Erzeugt eine animierte Leaflet-Karte, die zeigt, wie sich der geografische Sterbepunkt-Schwerpunkt der Familie im Zeitverlauf verschiebt.",
        "input":   "Sterbeorte + Koordinaten aus 'Buch-Statistiken'.",
        "output":  "HTML-Datei mit Leaflet-Animation (ein Frame pro Dekade).",
        "details": "Benötigt 'Buch-Statistiken' als Vorgänger-Task. Eignet sich besonders für Auswanderer-Familien.",
    },
    "export_cousins_map": {
        "title":   "Karte: Lebende Cousins nach US-County",
        "group":   "Export",
        "purpose": "Leaflet-Karte mit Kreisen pro US-County — Kreisgröße entspricht der Anzahl lebender Verwandter in diesem County.",
        "input":   "Cousin-Analyse-Ergebnisse aus 'Buch-Statistiken'.",
        "output":  "HTML-Datei mit interaktiver Leaflet-Karte.",
        "details": "Benötigt 'Buch-Statistiken' aktiv. Sinnvoll für Familien mit starker US-Auswanderung.",
    },
}


# ── CLI-Subbefehle ────────────────────────────────────────────────────────────

CLI_HELP = {
    "--mrca": {
        "title":   "MRCA-Finder (CLI)",
        "syntax":  "python main.py --mrca @I100@ @I200@",
        "purpose": "Findet den jüngsten gemeinsamen Vorfahren (MRCA) zweier Personen — direkt aus der Konsole.",
        "details": "Lädt die GEDCOM, sucht beide Personen, gibt MRCA-ID, deren Tiefen, Verwandtschafts-Label und beide Pfade aus.",
        "example": "python main.py --mrca @I251@ @I2475@\n→ MRCA: @I42@ (Cousin 3. Grades, depth_a=4, depth_b=4)",
    },
    "--merge": {
        "title":   "Zwei GEDCOMs zusammenführen (CLI)",
        "syntax":  "python main.py --merge fileA.ged fileB.ged --merge-out merged.ged",
        "purpose": "Mergt zwei GEDCOMs mit Doubletten-Resolution (Name+Geburtsjahr ±2).",
        "details": "Schreibt ein Sidecar-Log .merge.log mit Liste der zusammengeführten Paare.",
    },
    "--predict-cm": {
        "title":   "DNA-cM → Verwandtschaft (CLI)",
        "syntax":  "python main.py --predict-cm 850",
        "purpose": "Wandelt einen gemessenen DNA-cM-Wert in Verwandtschafts-Wahrscheinlichkeiten um.",
        "details": "Gibt Top-5 Beziehungen mit Wahrscheinlichkeit (Gaussian-basiert) aus. 850 cM → 'Cousin 1. Grades' ~99%.",
    },
    "--batch": {
        "title":   "Batch-Modus (CLI ohne GUI)",
        "syntax":  "python main.py --batch [--tasks t1,t2,…] [--gedfile X] [--root-id Y]",
        "purpose": "Führt alle (oder ausgewählte) Tasks ohne GUI aus. Für Scheduled Tasks / Cron.",
        "details": "Exit-Codes: 0=OK, 1=Task-Fehler, 2=Unbekannte Task-ID, 130=User-Abbruch.",
    },
    "--list-tasks": {
        "title":   "Liste aller Tasks (CLI)",
        "syntax":  "python main.py --list-tasks",
        "purpose": "Zeigt alle verfügbaren Tasks mit ID, Gruppe, Default-Status.",
        "details": "* markiert Default-Tasks (laufen ohne --tasks).",
    },
}


# ── Mathematische Konzepte (für die Hilfe) ────────────────────────────────────

CONCEPTS = {
    "Kinship-Koeffizient Φ": {
        "definition": "Wahrscheinlichkeit, dass ein zufällig gewähltes Allel von Person A IBD (identical by descent) ist mit einem zufällig gewählten Allel von B.",
        "formula":    "Henderson Tabular: Φ(A,A) = (1+F)/2; Φ(A,B) = ½·[Φ(P_jünger,B) + Φ(M_jünger,B)]",
        "examples":   "Φ(Eltern, Kind) = 0.25 · Φ(Vollgeschwister) = 0.25 · Φ(Großeltern, Enkel) = 0.125 · Φ(Cousin 1°) = 1/16",
    },
    "Wright's F (Inzuchtkoeffizient)": {
        "definition": "Wahrscheinlichkeit, dass eine Person an einem Genort zwei IBD-Allele trägt.",
        "formula":    "F(X) = Σ über gemeinsame Ahnen C der Eltern: (½)^(L_F + L_M + 1) × (1+F_C)",
        "examples":   "F=0 ohne Konsanguinität · F=1/16 bei Cousin-1°-Ehe-Kind · F=1/4 bei Geschwister-Ehe-Kind",
    },
    "Sosa-Stradonitz-Nummerierung": {
        "definition": "Internationaler Standard für Ahnen-Nummerierung: Proband = 1, Vater von N = 2N, Mutter von N = 2N+1.",
        "formula":    "Generation = bit_length(sosa) − 1.  Beispiel: Sosa 12 → bit_length(12)=4 → Gen 3 (Urgroßeltern).",
        "examples":   "Du=1, Vater=2, Mutter=3, paternaler Großvater=4, paternale Großmutter=5, …",
    },
    "DNA-cM (Centi-Morgan)": {
        "definition": "Einheit der DNA-Erbeinheit. Gesamtes menschliches Genom ≈ 7000 cM. Geteilte cM zwischen 2 Personen ≈ Φ × 2 × 7000.",
        "formula":    "Erwartete cM(A,B) = 2 × Φ(A,B) × 7000",
        "examples":   "Eltern/Kind ~3500 cM · Vollgeschwister ~2600 · Cousin 1° ~875 · Cousin 3° ~75",
    },
    "Pedigree Collapse (Implex)": {
        "definition": "Generationen-Effekt, dass eine Person mehrfach als Ahn auftritt (wenn Vorfahren miteinander verwandt sind).",
        "formula":    "Collapse-Rate Gen N = 1 − (eindeutige Ahnen / 2^N)",
        "examples":   "Gen 12: theoretisch 4096 Slots — bei 5% Collapse: ~3890 eindeutige Personen",
    },
}
